module.exports = global.store = {
  current_volume: 43,
  lineChart: {
    categories: [
      "01 Dec",
      "02 Dec",
      "03 Dec",
      "04 Dec",
      "05 Dec",
      "06 Dec",
      "07 Dec",
      "08 Dec",
      "09 Dec",
    ],
    series: [
      {
        name: "Koppar kaffe",
        data: [12, 13, 16, 9, 15, 14, 12, 11, 9],
      },
    ],
  },
  leaderboards: {
    week: [
      { name: "Person1 Person1 Person1 Person1 Person1Person1 ", score: "25" },
      { name: "Person2", score: "18" },
      { name: "Person3", score: "16" },
      { name: "Person4", score: "16" },
      { name: "Person5", score: "14" },
      { name: "Person6", score: "13" },
      { name: "Person7", score: "12" },
      { name: "Person8", score: "9" },
      { name: "Person9", score: "8" },
      { name: "Person10", score: "7" },
      { name: "Person11", score: "7" },
      { name: "Person12", score: "5" },
      { name: "Person13", score: "5" },
      { name: "Person14", score: "5" },
      { name: "Person15", score: "4" },
      { name: "Person16", score: "4" },
      { name: "Person17", score: "3" },
      { name: "Person18", score: "2" },
      { name: "Person19", score: "2" },
      { name: "Person20", score: "2" },
      { name: "Person21", score: "1" },
      { name: "Person22", score: "1" },
    ],
  },
};
